name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Vérifie le code source (Git checkout)
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2: Configuration de Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' # Spécifie la distribution Java

      # Étape 3: Aller dans le répertoire du projet Maven
      - name: Change to project directory
        run: cd ./Code-Review # Change './Code-Review' si ton fichier pom.xml est ailleurs

      # Étape 4: Installer Maven et compiler le projet
      - name: Build with Maven
        run: mvn clean install -DskipTests=true
        working-directory: ./Code-Review # Indique le répertoire contenant le pom.xml

      # Étape 5: Exécution des tests unitaires
      - name: Run unit tests
        run: mvn test
        working-directory: ./Code-Review

      # Étape 6: Vérifier la qualité du code avec Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check
        working-directory: ./Code-Review

      # Étape 7: Générer le rapport Cobertura (test coverage)
      - name: Generate Cobertura report
        run: mvn cobertura:cobertura
        working-directory: ./Code-Review

      # Étape 8: Déployer si tout est réussi
      - name: Deploy to Maven repository
        if: success() && github.ref == 'refs/heads/main'
        run: mvn deploy -DskipTests
        working-directory: ./Code-Review
