name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true
        working-directory: ./AwesomePasswordChecker

      - name: Run unit tests
        run: mvn test
        working-directory: ./AwesomePasswordChecker

      - name: Run Checkstyle
        run: mvn checkstyle:check
        working-directory: ./AwesomePasswordChecker

      - name: Generate JaCoCo report
        run: mvn jacoco:report
        working-directory: ./AwesomePasswordChecker
  


